/**
 * Demo product catalog — the ONLY source for example items shown anywhere in
 * the product (marketing pages, Remotion videos, empty states, previews).
 *
 * Every entry's title was written by looking at the actual photo: the label
 * always matches what is visibly in the image (brand text verified where
 * present). The newly sourced primary reseller set has per-file license and
 * transformation records in docs/demo-asset-provenance.md; older library
 * entries retain their original repo provenance.
 *
 * Rules for consumers:
 * - Pick products via DEMO_SURFACE_ASSIGNMENTS. Prefer the audience's clearest
 *   category story over artificial cross-surface uniqueness; a strong reseller
 *   example may repeat when it is the honest best fit.
 * - Never relabel an image — if you need a different product, add a new
 *   verified photo + entry instead.
 *
 * This module is intentionally directive-free (no "use client") so it can be
 * imported from server and client components alike.
 */

export type DemoProduct = {
  slug: string;
  /** Path under /public — usable directly as an <img src>. */
  image: string;
  /** Listing-style title; matches what the photo actually shows. */
  title: string;
  /** Short display name for tight UI (chips, mini-cards). */
  shortName: string;
  /** Realistic used-market price in USD. */
  price: number;
  condition: "Like new" | "Good" | "Fair";
  category: string;
  /** Which pricing tier the pipeline would plausibly fire for this item. */
  pricingStory: "barcode" | "comps" | "depreciation";
  /** 2-3 short attribute bullets — only what is actually visible in the photo. */
  details: string[];
  alt: string;
};

export const DEMO_PRODUCTS: DemoProduct[] = [
  {
    slug: "camera",
    image: "/demo/camera.jpg",
    title: "Canon EOS 80D DSLR with 50mm lens",
    shortName: "Canon EOS 80D",
    price: 429,
    condition: "Good",
    category: "Cameras & Photo",
    pricingStory: "comps",
    details: ["Canon EOS 80D digital SLR", "50mm prime lens included", "Model badge readable on the body"],
    alt: "Black Canon EOS 80D DSLR camera with a prime lens on a wooden table",
  },
  {
    slug: "sneakers",
    image: "/demo/sneakers.jpg",
    title: "Nike Invincible Run 3, grey and orange",
    shortName: "Nike Invincible 3",
    price: 48,
    condition: "Good",
    category: "Clothing & Shoes",
    pricingStory: "comps",
    details: ["Nike Invincible Run 3 running shoes", "Grey knit upper, orange sole", "Worn, scuffing on the sole"],
    alt: "Close-up of worn grey and orange Nike Invincible Run 3 running shoes on concrete",
  },
  {
    slug: "book",
    image: "/demo/book.jpg",
    title: "Python for Unix and Linux System Administration (O'Reilly)",
    shortName: "O'Reilly Python",
    price: 24,
    condition: "Good",
    category: "Books",
    pricingStory: "barcode",
    details: ["O'Reilly programming paperback", "Title fully readable on the cover", "Standard trade-paperback format"],
    alt: "Person holding the O'Reilly Python for Unix and Linux System Administration book",
  },
  {
    slug: "vinyl",
    image: "/demo/vinyl.jpg",
    title: "Limited teal-pressing vinyl LP",
    shortName: "Teal vinyl LP",
    price: 28,
    condition: "Like new",
    category: "Music & Vinyl",
    pricingStory: "comps",
    details: ["LP pressed in translucent teal", "Limited color pressing", "Photographed on a turntable"],
    alt: "Teal colored vinyl record spinning on a turntable in warm light",
  },
  {
    slug: "gameboy",
    image: "/demo/gameboy.jpg",
    title: "Nintendo Game Boy Color, Pokémon edition",
    shortName: "Game Boy Color",
    price: 110,
    condition: "Good",
    category: "Video Games & Consoles",
    pricingStory: "comps",
    details: ["Nintendo Game Boy Color, yellow Pokémon edition", "Pikachu graphic on the shell", "Screen and buttons intact"],
    alt: "Yellow Pokémon-edition Nintendo Game Boy Color resting on a pile of Pokémon cards",
  },
  {
    slug: "keyboard",
    image: "/demo/keyboard.jpg",
    title: "Custom 65% mechanical keyboard, green & white keycaps",
    shortName: "65% mech keyboard",
    price: 120,
    condition: "Like new",
    category: "Computers & Accessories",
    pricingStory: "depreciation",
    details: ["Compact 65% layout", "Green and white keycap set", "Custom-built mechanical board"],
    alt: "Custom 65 percent mechanical keyboard with green and white keycaps on a desk mat",
  },
  {
    slug: "headphones",
    image: "/demo/headphones.jpg",
    title: "Black over-ear wireless headphones",
    shortName: "Wireless headphones",
    price: 55,
    condition: "Good",
    category: "Consumer Electronics",
    pricingStory: "comps",
    details: ["Over-ear wireless headphones", "Matte black with a cream inner band", "Lightly used, works fully"],
    alt: "Black over-ear wireless headphones with a cream inner band on a worn wooden table",
  },
  {
    slug: "guitar",
    image: "/demo/guitar.jpg",
    title: "Taylor koa acoustic-electric guitar with cutaway",
    shortName: "Taylor acoustic",
    price: 895,
    condition: "Like new",
    category: "Musical Instruments",
    pricingStory: "comps",
    details: ["Taylor acoustic-electric", "Gloss koa top with cutaway", "Taylor logo on the headstock"],
    alt: "Taylor koa-wood acoustic-electric guitar on a stand beside a window",
  },
  {
    slug: "polaroid",
    image: "/demo/polaroid.jpg",
    title: "Polaroid 636 CloseUp instant camera",
    shortName: "Polaroid 636",
    price: 65,
    condition: "Good",
    category: "Cameras & Photo",
    pricingStory: "comps",
    details: ["Polaroid 636 CloseUp instant camera", "Classic black 600-series body", "Held in hand, fully shown"],
    alt: "Hand holding a black vintage Polaroid 636 CloseUp instant camera against a cork wall",
  },
  {
    slug: "mixer",
    image: "/demo/mixer.jpg",
    title: "KitchenAid stand mixer, pink",
    shortName: "KitchenAid mixer",
    price: 185,
    condition: "Good",
    category: "Home & Kitchen",
    pricingStory: "comps",
    details: ["Pink KitchenAid tilt-head stand mixer", "Glass mixing bowl included", "Brand printed on the head"],
    alt: "Blush-pink KitchenAid stand mixer with a glass bowl on a home kitchen counter",
  },
  {
    slug: "chess",
    image: "/demo/chess.jpg",
    title: "Vintage brass figural chess set on wooden board",
    shortName: "Brass chess set",
    price: 75,
    condition: "Fair",
    category: "Toys & Games",
    pricingStory: "depreciation",
    details: ["Vintage brass figural pieces", "Wooden chessboard included", "Ornate cast detailing"],
    alt: "Ornate vintage brass chess pieces standing on a wooden chessboard",
  },
  {
    slug: "turntable",
    image: "/demo/turntable.jpg",
    title: "Victrola belt-drive turntable, silver",
    shortName: "Victrola turntable",
    price: 68,
    condition: "Good",
    category: "Audio & Hi-Fi",
    pricingStory: "comps",
    details: ["Victrola belt-drive turntable", "Silver plinth, brand printed", "Record shown on the platter"],
    alt: "Silver Victrola belt-drive turntable with a vinyl record on the platter, beside a sketchpad",
  },
  {
    slug: "espresso",
    image: "/demo/espresso.jpg",
    title: "Sage Barista espresso machine with built-in grinder",
    shortName: "Espresso machine",
    price: 280,
    condition: "Good",
    category: "Home & Kitchen",
    pricingStory: "comps",
    details: ["Stainless espresso machine with built-in grinder", "Portafilter, tamper, and tamping station", "Used with light patina, runs well"],
    alt: "Used stainless Sage Barista espresso machine with a built-in grinder on a sunlit kitchen counter",
  },
  {
    slug: "gshock",
    image: "/demo/gshock.jpg",
    title: "Casio G-Shock DW-5600 digital watch",
    shortName: "G-Shock DW-5600",
    price: 42,
    condition: "Good",
    category: "Watches",
    pricingStory: "comps",
    details: ["Casio G-Shock DW-5600", "Classic square case", "Digital display, resin strap"],
    alt: "Hand holding a black Casio G-Shock DW-5600 digital watch",
  },
  // --- r6: visibly-USED items (owner: the carousel should reinforce that ---
  // --- SnapList sells secondhand — worn, dusty, broken-in, not showroom) ---
  {
    slug: "macbook",
    image: "/demo/macbook.jpg",
    title: "Apple MacBook Pro 13-inch, Retina display",
    shortName: "MacBook Pro 13″",
    price: 295,
    condition: "Good",
    category: "Computers & Accessories",
    pricingStory: "comps",
    details: ["Apple MacBook Pro 13-inch", "macOS menu bar on screen", "Silver aluminum unibody"],
    alt: "Open Apple MacBook Pro 13-inch sitting on an outdoor wooden table",
  },
  {
    slug: "boots",
    image: "/demo/boots.jpg",
    title: "Tan leather lace-up boots, broken in",
    shortName: "Leather boots",
    price: 58,
    condition: "Fair",
    category: "Clothing & Shoes",
    pricingStory: "comps",
    details: ["Tan leather lace-up boots", "Visible wear at the toes", "Lug rubber outsoles"],
    alt: "Person lacing up a pair of worn tan leather boots on asphalt",
  },
  {
    slug: "bicycle",
    image: "/demo/bicycle.jpg",
    title: "Vintage Peugeot single-speed road bike",
    shortName: "Peugeot road bike",
    price: 240,
    condition: "Good",
    category: "Sporting Goods",
    pricingStory: "comps",
    details: ["Peugeot decal on the frame", "Single-speed drivetrain", "Brown leather saddle and grips"],
    alt: "Silver vintage Peugeot single-speed bicycle leaning against a dark wall",
  },
  {
    slug: "drill",
    image: "/demo/drill.jpg",
    title: "Milwaukee M18 cordless drill with XC battery",
    shortName: "Milwaukee M18 drill",
    price: 79,
    condition: "Good",
    category: "Tools & Workshop",
    pricingStory: "comps",
    details: ["Milwaukee M18 cordless drill", "REDLITHIUM XC battery pack", "Honest jobsite dust and wear"],
    alt: "Red Milwaukee M18 cordless drill lying on a dusty workshop floor",
  },
  {
    slug: "skateboard",
    image: "/demo/skateboard.jpg",
    title: "Complete skateboard, multicolor graphic deck",
    shortName: "Skateboard",
    price: 45,
    condition: "Fair",
    category: "Sporting Goods",
    pricingStory: "depreciation",
    details: ["Complete with trucks and wheels", "Multicolor graphic deck", "Wear consistent with regular use"],
    alt: "Skateboard with a colorful graphic deck leaning against a yellow wall",
  },
  {
    slug: "crt-tv",
    image: "/demo/crt-tv.jpg",
    title: "Vintage Sampo solid-state CRT TV, orange",
    shortName: "Sampo CRT TV",
    price: 85,
    condition: "Fair",
    category: "Vintage Electronics",
    pricingStory: "comps",
    details: ["Sampo solid-state CRT set", "Bright orange cabinet", "Dial tuner and side speaker grille"],
    alt: "Retro orange Sampo solid-state CRT television on a wooden shelf",
  },
  {
    slug: "backpack",
    image: "/demo/backpack.jpg",
    title: "Olive everyday daypack with leather patch",
    shortName: "Olive daypack",
    price: 38,
    condition: "Good",
    category: "Bags & Luggage",
    pricingStory: "depreciation",
    details: ["Olive-green everyday daypack", "Tan leather accent patch", "Orange-lined zip pockets"],
    alt: "Worn olive-green everyday daypack on a sunlit wooden bench",
  },
  // --- r6: expanded authentic set (sourced license-clean from Unsplash/Pexels,
  // --- real-seller look) so the carousel + surfaces stay varied and unique ---
  {
    slug: "lamp",
    image: "/demo/lamp.jpg",
    title: "Brass gooseneck desk lamp with dome shade",
    shortName: "Brass desk lamp",
    price: 34,
    condition: "Good",
    category: "Home & Garden",
    pricingStory: "depreciation",
    details: ["Antique-brass finish", "Adjustable gooseneck arm", "Weighted round base"],
    alt: "Brass gooseneck desk lamp lit over an open book on a desk",
  },
  {
    slug: "typewriter",
    image: "/demo/typewriter.jpg",
    title: "Vintage Corona manual typewriter, black",
    shortName: "Corona typewriter",
    price: 145,
    condition: "Fair",
    category: "Vintage Electronics",
    pricingStory: "comps",
    details: ["Corona badge on the body", "Glossy black portable frame", "Round glass-top keys"],
    alt: "Vintage black Corona manual typewriter on a dark rustic wood surface",
  },
  {
    slug: "jacket",
    image: "/demo/jacket.jpg",
    title: "Black moto leather jacket",
    shortName: "Moto jacket",
    price: 42,
    condition: "Good",
    category: "Clothing & Shoes",
    pricingStory: "depreciation",
    details: ["Asymmetric zip moto styling", "Snap collar and zip cuffs", "Worn-in creasing"],
    alt: "Black moto leather jacket on a hanger over dark draped fabric",
  },
  {
    slug: "skillet",
    image: "/demo/skillet.jpg",
    title: "Cast iron skillet with crocheted handle cover",
    shortName: "Cast iron skillet",
    price: 22,
    condition: "Good",
    category: "Home & Kitchen",
    pricingStory: "depreciation",
    details: ["Seasoned cast iron pan", "Knit handle sleeve included", "Honest cooking patina"],
    alt: "Black cast iron skillet with a knit handle cover on a stovetop",
  },
  {
    slug: "plant",
    image: "/demo/plant.jpg",
    title: "Variegated snake plant in a ceramic pot",
    shortName: "Snake plant",
    price: 18,
    condition: "Like new",
    category: "Home & Garden",
    pricingStory: "depreciation",
    details: ["Yellow-edged sansevieria leaves", "Cream glazed ceramic pot", "Healthy upright growth"],
    alt: "Variegated snake plant in a cream ceramic pot on a tiled table",
  },
  {
    slug: "racket",
    image: "/demo/racket.jpg",
    title: "Babolat tennis racket with ball",
    shortName: "Babolat racket",
    price: 60,
    condition: "Good",
    category: "Sporting Goods",
    pricingStory: "comps",
    details: ["Babolat branding on the throat", "Blue and black frame", "Tennis ball included"],
    alt: "Babolat blue and black tennis racket with a ball on a green court",
  },
  {
    slug: "chair",
    image: "/demo/chair.jpg",
    title: "Rolling office task chair",
    shortName: "Office chair",
    price: 25,
    condition: "Fair",
    category: "Furniture",
    pricingStory: "depreciation",
    details: ["Five-star rolling base", "Padded armrests", "Honest wear on the seat"],
    alt: "Worn rolling office task chair in a dim room",
  },
  {
    slug: "boombox",
    image: "/demo/boombox.jpg",
    title: "Vintage Sharp radio cassette boombox, red",
    shortName: "Sharp boombox",
    price: 95,
    condition: "Fair",
    category: "Vintage Electronics",
    pricingStory: "comps",
    details: ["Sharp badge on the front", "Red dual-speaker cassette deck", "Telescopic antennas"],
    alt: "Vintage red Sharp radio cassette boombox on a wooden shelf among plants",
  },
  {
    slug: "watch",
    image: "/demo/watch.jpg",
    title: "Timex chronograph watch, tan leather strap",
    shortName: "Timex chronograph",
    price: 48,
    condition: "Good",
    category: "Watches",
    pricingStory: "comps",
    details: ["Timex dial branding", "Black face with chronograph subdials", "Tan leather strap"],
    alt: "Hand holding a Timex chronograph watch with a tan leather strap",
  },
  {
    slug: "vase",
    image: "/demo/vase.jpg",
    title: "Speckled stoneware ceramic vase",
    shortName: "Ceramic vase",
    price: 28,
    condition: "Good",
    category: "Home & Garden",
    pricingStory: "depreciation",
    details: ["Speckled grey stoneware", "Matte handmade-style glaze", "Single stem vase"],
    alt: "Single speckled grey stoneware vase on a stone shelf in sunlight",
  },
  // r6.1: four authentic used-item photos sourced to break asset reuse across
  // surfaces. The static home/tour spots that used to borrow a video clip's
  // item (three-moves↔step-price, storefront↔step-publish, waterfall↔step-snap)
  // now use these instead, so no product appears on two surfaces.
  // r7: filmcamera is now the how-it-works pipeline's single hero item — it
  // runs through all six step clips (snap → identify → price → write → publish
  // → answer). Its readable "Canon"/"AE-1" markings drive the identify OCR and
  // it has real resale comps for the price step.
  {
    slug: "rollerskates",
    image: "/demo/rollerskates.jpg",
    title: "Denim quad roller skates, light wash blue, women's 8",
    shortName: "Quad roller skates",
    price: 75,
    condition: "Good",
    category: "Sporting Goods",
    pricingStory: "comps",
    details: ["Light-wash denim boot with tan heel", "Cream wheels, lightly worn", "Smooth rolling, no cracks"],
    alt: "A pair of light-blue denim quad roller skates with cream wheels on a concrete ledge against a brick wall",
  },
  {
    slug: "console",
    image: "/demo/console.jpg",
    title: "Nintendo Switch console with neon blue & red Joy-Cons + dock",
    shortName: "Nintendo Switch",
    price: 175,
    condition: "Good",
    category: "Video Games & Consoles",
    pricingStory: "comps",
    details: ["Includes original dock and both neon Joy-Con controllers", "Powers on and works, screen has no cracks", "Light wear from normal home use"],
    alt: "A used Nintendo Switch with neon blue and red Joy-Cons in its dock on a wooden desk",
  },
  {
    slug: "dutchoven",
    image: "/demo/dutchoven.jpg",
    title: "Le Creuset 4.5qt enameled cast iron Dutch oven, Caribbean teal",
    shortName: "Le Creuset Dutch oven",
    price: 185,
    condition: "Good",
    category: "Kitchen & Dining",
    pricingStory: "comps",
    details: ["Enameled cast iron, about 4.5 qt round", "Caribbean teal-blue exterior", "Lightly used, no chips or cracks"],
    alt: "A teal enameled cast iron Dutch oven with its lid on, sitting on a home gas stovetop",
  },
  {
    slug: "filmcamera",
    image: "/demo/filmcamera.jpg",
    title: "Canon AE-1 35mm film SLR camera with 50mm f/1.8 FD lens",
    shortName: "Canon AE-1",
    price: 165,
    condition: "Good",
    category: "Cameras & Photo",
    pricingStory: "comps",
    details: ["Includes Canon FD 50mm lens with front cap and original strap", "Chrome body shows light cosmetic wear, all controls intact", "Classic 1976 manual-focus 35mm film SLR"],
    alt: "A vintage silver and black Canon AE-1 35mm film camera with a 50mm lens and strap on a dark wooden surface at golden hour",
  },
  // r6.1: three more authentic photos so the logged-in dashboard folder stops
  // borrowing the home scan's items (gshock/espresso/turntable). These three
  // are exclusive to the dashboard.
  {
    slug: "kettlebell",
    image: "/demo/kettlebell.jpg",
    title: "Cast iron kettlebell, 35 lb / 16 kg",
    shortName: "Kettlebell",
    price: 30,
    condition: "Good",
    category: "Sporting Goods",
    pricingStory: "comps",
    details: ["35 lb / 16 kg cast iron", "Single-cast handle, no chips or cracks", "Light surface wear from home use"],
    alt: "A single black cast iron 35 lb kettlebell resting on a mat on the floor in natural window light",
  },
  {
    slug: "binoculars",
    image: "/demo/binoculars.jpg",
    title: "Antique French opera glasses, brass and leather",
    shortName: "Binoculars",
    price: 48,
    condition: "Good",
    category: "Cameras & Photo",
    pricingStory: "comps",
    details: ["Vintage brass and leather barrels", "Engraved 'PARIS' on the eyepiece ring", "Compact opera/field glass style, glass intact"],
    alt: "Vintage brass and leather opera-glass binoculars resting on a polished wooden table in natural light",
  },
  {
    slug: "sewingmachine",
    image: "/demo/sewingmachine.jpg",
    title: "Brother 1034D serger overlock sewing machine with manual",
    shortName: "Sewing machine",
    price: 135,
    condition: "Good",
    category: "Crafts",
    pricingStory: "comps",
    details: ["Brother Lock 1034D 3/4-thread serger", "Includes original instruction manual", "Color-coded threading guides intact"],
    alt: "A used Brother 1034D serger sewing machine on a wooden table by a window with its manual open in front of it",
  },
  // ===== AUTHENTIC FB-Marketplace assets (2026-06 overhaul): real used
  // items from the owner's two Marketplace accounts, uniform 1080² masters,
  // price overlays curated out. Grounded titles/specs from the listing data. =====
  {
    slug: "a-macbookair",
    image: "/demo/authentic/a-macbookair.jpg",
    title: "Apple MacBook Air (M1), 13-inch",
    shortName: "Apple MacBook Air (M1)",
    price: 600,
    condition: "Good",
    category: "Computers & Accessories",
    pricingStory: "comps",
    details: ["Apple MacBook Air, M1 chip", "13-inch Retina, silver", "Powers on, light desk wear"],
    alt: "Open silver Apple MacBook Air on a desk showing the macOS desktop",
  },
  {
    slug: "a-cyberpc",
    image: "/demo/authentic/a-cyberpc.jpg",
    title: "CyberPowerPC gaming desktop, tempered-glass case",
    shortName: "CyberPowerPC gaming",
    price: 520,
    condition: "Good",
    category: "Computers & Accessories",
    pricingStory: "comps",
    details: ["CyberPowerPC tower build", "Tempered-glass side panel", "RGB-ready gaming desktop"],
    alt: "Black CyberPowerPC gaming desktop with a tempered-glass side panel",
  },
  {
    slug: "a-monitors",
    image: "/demo/authentic/a-monitors.jpg",
    title: "Pair of computer monitors with stands",
    shortName: "Two computer monitors",
    price: 120,
    condition: "Good",
    category: "Computers & Accessories",
    pricingStory: "depreciation",
    details: ["Two matching widescreen monitors", "Stands included", "Clean screens, tested"],
    alt: "Two matching computer monitors side by side on a desk",
  },
  {
    slug: "a-powerblock",
    image: "/demo/authentic/a-powerblock.jpg",
    title: "PowerBlock adjustable dumbbells with stand",
    shortName: "PowerBlock adjustable",
    price: 250,
    condition: "Good",
    category: "Sporting Goods",
    pricingStory: "comps",
    details: ["PowerBlock adjustable dumbbell set", "Selector pins + stand", "Replaces a full dumbbell rack"],
    alt: "A pair of PowerBlock adjustable dumbbells resting on their stand",
  },
  {
    slug: "a-breadmaker",
    image: "/demo/authentic/a-breadmaker.jpg",
    title: "Automatic bread maker, white",
    shortName: "Automatic bread maker",
    price: 30,
    condition: "Good",
    category: "Home & Kitchen",
    pricingStory: "comps",
    details: ["Countertop bread machine", "Digital control panel", "Pan and paddle included"],
    alt: "A white automatic bread maker on a counter",
  },
  {
    slug: "a-carseat",
    image: "/demo/authentic/a-carseat.jpg",
    title: "Britax Boulevard 70 CS convertible car seat",
    shortName: "Britax Boulevard 70 CS",
    price: 70,
    condition: "Good",
    category: "Baby & Kids",
    pricingStory: "comps",
    details: ["Britax Boulevard 70 CS, model readable on top", "Grey fabric, padded side wings", "Harness and warning labels intact"],
    alt: "A grey Britax Boulevard 70 CS convertible car seat standing on patterned carpet",
  },
  {
    slug: "a-roadbike",
    image: "/demo/authentic/a-roadbike.jpg",
    title: "Single-speed cruiser bike",
    shortName: "Single-speed cruiser bike",
    price: 80,
    condition: "Good",
    category: "Bicycles",
    pricingStory: "comps",
    details: ["Single-speed cruiser bike", "Swept-back handlebars", "Rides well, honest patina"],
    alt: "A cream single-speed cruiser bicycle leaning against a decorative wall",
  },
  {
    slug: "a-martini",
    image: "/demo/authentic/a-martini.jpg",
    title: "Set of martini glasses, boxed",
    shortName: "Set of martini glasses",
    price: 15,
    condition: "Like new",
    category: "Home & Kitchen",
    pricingStory: "depreciation",
    details: ["Set of stemmed martini glasses", "Original box", "No chips or cracks"],
    alt: "A boxed set of stemmed martini glasses",
  },
  {
    slug: "a-scooter",
    image: "/demo/authentic/a-scooter.jpg",
    title: "District kick scooter",
    shortName: "District kick scooter",
    price: 35,
    condition: "Good",
    category: "Sporting Goods",
    pricingStory: "depreciation",
    details: ["District-brand kick scooter", "White deck, red wheels", "Rolls smooth, light wear"],
    alt: "A District kick scooter standing on a driveway",
  },
  {
    slug: "a-yellowbike",
    image: "/demo/authentic/a-yellowbike.jpg",
    title: "20-inch kids' mountain bike, yellow",
    shortName: "20-inch kids' bike",
    price: 80,
    condition: "Good",
    category: "Bicycles",
    pricingStory: "comps",
    details: ["20-inch kids' mountain bike", "Yellow frame, knobby tires", "Rides well, normal wear"],
    alt: "A yellow 20-inch kids' mountain bike outdoors",
  },
  {
    slug: "a-xboxpads",
    image: "/demo/authentic/a-xboxpads.jpg",
    title: "Xbox One wireless controllers, set of 2",
    shortName: "Xbox One wireless",
    price: 45,
    condition: "Good",
    category: "Video Games & Consoles",
    pricingStory: "comps",
    details: ["Two Xbox One wireless controllers", "One black, one white", "Tested, both work"],
    alt: "Two Xbox One wireless controllers, one black and one white",
  },
  {
    slug: "a-speakers",
    image: "/demo/authentic/a-speakers.jpg",
    title: "Desktop computer speakers, black pair",
    shortName: "Desktop computer speakers",
    price: 20,
    condition: "Good",
    category: "Computers & Accessories",
    pricingStory: "depreciation",
    details: ["Pair of powered desktop speakers", "Compact black cabinets", "Cabling included"],
    alt: "A pair of black desktop computer speakers on a wood floor",
  },
  {
    slug: "a-ceilinglight",
    image: "/demo/authentic/a-ceilinglight.jpg",
    title: "Brushed-brass semi-flush ceiling light",
    shortName: "Brushed-brass semi-flush",
    price: 30,
    condition: "Good",
    category: "Home & Garden",
    pricingStory: "depreciation",
    details: ["Brass-finish semi-flush fixture", "Frosted glass bowl shade", "Three-arm mount"],
    alt: "A brushed-brass ceiling light fixture with a frosted glass shade",
  },
  {
    slug: "a-cooler",
    image: "/demo/authentic/a-cooler.jpg",
    title: "Hard-side cooler, blue and white",
    shortName: "Hard-side cooler",
    price: 20,
    condition: "Good",
    category: "Sporting Goods",
    pricingStory: "depreciation",
    details: ["Blue and white hard cooler", "Hinged lid", "Holds ice well"],
    alt: "A blue and white hard-side cooler",
  },
  {
    slug: "a-microwave",
    image: "/demo/authentic/a-microwave.jpg",
    title: "Countertop microwave, white",
    shortName: "Countertop microwave",
    price: 40,
    condition: "Good",
    category: "Home & Kitchen",
    pricingStory: "depreciation",
    details: ["White countertop microwave", "Digital keypad", "Tested, heats evenly"],
    alt: "A white countertop microwave",
  },
  {
    slug: "a-fridge",
    image: "/demo/authentic/a-fridge.jpg",
    title: "Stainless top-freezer refrigerator",
    shortName: "Stainless top-freezer",
    price: 300,
    condition: "Good",
    category: "Appliances",
    pricingStory: "comps",
    details: ["Stainless top-freezer fridge", "Adjustable interior shelves", "Runs cold, clean"],
    alt: "A stainless steel top-freezer refrigerator",
  },
  {
    slug: "a-wardrobe",
    image: "/demo/authentic/a-wardrobe.jpg",
    title: "White wardrobe storage cabinet",
    shortName: "White wardrobe storage",
    price: 90,
    condition: "Good",
    category: "Furniture",
    pricingStory: "depreciation",
    details: ["Tall white wardrobe cabinet", "Hanging space and shelf", "Solid, minor wear"],
    alt: "A tall white wardrobe storage cabinet",
  },
  {
    slug: "a-dresser",
    image: "/demo/authentic/a-dresser.jpg",
    title: "Dresser with mirror, dark wood",
    shortName: "Dresser with mirror",
    price: 180,
    condition: "Like new",
    category: "Furniture",
    pricingStory: "comps",
    details: ["Six-drawer dresser", "Matching mirror", "Like-new dark wood finish"],
    alt: "A dark wood dresser with an attached mirror",
  },
  {
    slug: "a-nightstand",
    image: "/demo/authentic/a-nightstand.jpg",
    title: "Nightstand, dark wood",
    shortName: "Nightstand",
    price: 60,
    condition: "Like new",
    category: "Furniture",
    pricingStory: "comps",
    details: ["Single-drawer nightstand", "Dark wood, matches a bedroom set", "Like new"],
    alt: "A dark wood nightstand",
  },
  {
    slug: "a-patioset",
    image: "/demo/authentic/a-patioset.jpg",
    title: "Glass-top patio table with wicker chairs",
    shortName: "Glass-top patio table",
    price: 120,
    condition: "Fair",
    category: "Patio & Garden",
    pricingStory: "depreciation",
    details: ["Glass-top outdoor table", "Woven wicker chairs", "Weathered but sturdy"],
    alt: "A glass-top patio table with woven wicker chairs",
  },
  {
    slug: "a-diningchairs",
    image: "/demo/authentic/a-diningchairs.jpg",
    title: "Dining chairs, black frame with wood seats",
    shortName: "Dining chairs",
    price: 40,
    condition: "Good",
    category: "Furniture",
    pricingStory: "depreciation",
    details: ["Black-painted wood frames", "Lattice backrest", "Warm wood seats"],
    alt: "A row of black dining chairs with lattice backs and wood seats on a deck",
  },
  {
    slug: "a-campchairs",
    image: "/demo/authentic/a-campchairs.jpg",
    title: "Folding camping chairs, red pair",
    shortName: "Folding camping chairs",
    price: 15,
    condition: "Good",
    category: "Sporting Goods",
    pricingStory: "depreciation",
    details: ["Two folding camp chairs", "Red fabric", "Sturdy frames"],
    alt: "Two red folding camping chairs",
  },
  {
    slug: "a-rug",
    image: "/demo/authentic/a-rug.jpg",
    title: "Patterned area rug, cream and black",
    shortName: "Patterned area rug",
    price: 35,
    condition: "Good",
    category: "Home & Garden",
    pricingStory: "depreciation",
    details: ["Large patterned area rug", "Cream field with border", "Clean, gently used"],
    alt: "A large cream and black patterned area rug",
  },
  {
    slug: "a-mattress",
    image: "/demo/authentic/a-mattress.jpg",
    title: "Quilted pillow-top mattress",
    shortName: "Quilted pillow-top",
    price: 120,
    condition: "Good",
    category: "Furniture",
    pricingStory: "comps",
    details: ["Quilted pillow-top mattress", "Clean, no stains", "Firm support"],
    alt: "A quilted pillow-top mattress",
  },
  {
    slug: "a-plant",
    image: "/demo/authentic/a-plant.jpg",
    title: "Trailing pothos houseplant",
    shortName: "Trailing pothos houseplant",
    price: 15,
    condition: "Like new",
    category: "Home & Garden",
    pricingStory: "depreciation",
    details: ["Healthy trailing pothos", "Long vines", "Easy-care houseplant"],
    alt: "A trailing pothos houseplant by a window",
  },
  {
    slug: "a-bedframe",
    image: "/demo/authentic/a-bedframe.jpg",
    title: "King bed frame with headboard, dark wood",
    shortName: "King bed frame with",
    price: 200,
    condition: "Like new",
    category: "Furniture",
    pricingStory: "comps",
    details: ["King bed frame and headboard", "Dark wood, matches set", "Like-new condition"],
    alt: "A dark wood king bed frame with a paneled headboard",
  },
  {
    slug: "a-hulahoop",
    image: "/demo/authentic/a-hulahoop.jpg",
    title: "Weighted fitness hula hoop, ~4 lb",
    shortName: "Weighted fitness hula hoop",
    price: 10,
    condition: "Good",
    category: "Sporting Goods",
    pricingStory: "comps",
    details: ["Weighted exercise hoop", "About 4 lb", "Padded segmented design"],
    alt: "A colorful weighted fitness hula hoop",
  },
  {
    slug: "a-crib",
    image: "/demo/authentic/a-crib.jpg",
    title: "Convertible baby crib, dark wood",
    shortName: "Convertible baby crib",
    price: 50,
    condition: "Like new",
    category: "Baby & Kids",
    pricingStory: "comps",
    details: ["Convertible wooden crib", "Adjustable mattress height", "Like new"],
    alt: "A dark wood convertible baby crib",
  },
  {
    slug: "a-stroller",
    image: "/demo/authentic/a-stroller.jpg",
    title: "Full-size baby stroller, black",
    shortName: "Full-size baby stroller",
    price: 20,
    condition: "Good",
    category: "Baby & Kids",
    pricingStory: "depreciation",
    details: ["Full-size black stroller", "Folds flat", "Works, light wear"],
    alt: "A folded black full-size baby stroller",
  },
  {
    slug: "a-litterbox",
    image: "/demo/authentic/a-litterbox.jpg",
    title: "Covered cat litter box, gray",
    shortName: "Covered cat litter box",
    price: 20,
    condition: "Good",
    category: "Pet Supplies",
    pricingStory: "depreciation",
    details: ["Gray plastic litter box", "High sides", "Clean"],
    alt: "A gray plastic covered cat litter box",
  },
  {
    slug: "a-bowls",
    image: "/demo/authentic/a-bowls.jpg",
    title: "Decorative leaf-shaped dishes, gold trim",
    shortName: "Decorative leaf dishes",
    price: 20,
    condition: "Good",
    category: "Home & Garden",
    pricingStory: "depreciation",
    details: ["Leaf-shaped serving dishes", "Black glass with gold-metal trim", "Set of four, display pieces"],
    alt: "A set of black glass leaf-shaped decorative dishes with gold trim",
  },
  {
    slug: "a-chest",
    image: "/demo/authentic/a-chest.jpg",
    title: "Tall 5-drawer chest of drawers, dark wood",
    shortName: "Tall 5-drawer chest of",
    price: 150,
    condition: "Like new",
    category: "Furniture",
    pricingStory: "comps",
    details: ["Five-drawer tall chest", "Dark wood, matches set", "Like new"],
    alt: "A tall dark wood five-drawer chest of drawers",
  },
  {
    slug: "a-xbox360",
    image: "/demo/authentic/a-xbox360.jpg",
    title: "Xbox 360 console with Kinect sensor, 2 controllers & game",
    shortName: "Xbox 360 Kinect bundle",
    price: 95,
    condition: "Good",
    category: "Video Games & Consoles",
    pricingStory: "comps",
    details: ["Xbox 360 console, model readable on the front", "Kinect sensor and two wireless controllers", "Includes a Kinect game, cables shown"],
    alt: "A black Xbox 360 console with a Kinect sensor, two controllers, and a Kinect game on a wood floor",
  },
  // Issue #136 licensed reseller set. These are newly sourced, locally hosted
  // Unsplash photographs selected at the actual 184px mobile and 300px desktop
  // card crops. Source, author, license, and transformation details live in
  // docs/demo-asset-provenance.md.
  {
    slug: "reseller-ps5",
    image: "/demo/reseller/ps5.webp",
    title: "Sony PlayStation 5 console with DualSense controller",
    shortName: "PlayStation 5 bundle",
    price: 379,
    condition: "Good",
    category: "Video Games & Consoles",
    pricingStory: "comps",
    details: [
      "PlayStation 5 console and DualSense controller",
      "White-and-black finish",
      "Console and controller shown together",
    ],
    alt: "White Sony PlayStation 5 console with a matching DualSense controller resting on top",
  },
  {
    slug: "reseller-dualsense",
    image: "/demo/reseller/dualsense.webp",
    title: "Sony PlayStation 5 DualSense wireless controller",
    shortName: "PS5 DualSense controller",
    price: 49,
    condition: "Good",
    category: "Video Games & Consoles",
    pricingStory: "comps",
    details: ["Sony DualSense controller", "White-and-black finish", "Buttons and thumbsticks shown clearly"],
    alt: "White and black Sony PlayStation 5 DualSense controller on a vivid red surface",
  },
  {
    slug: "reseller-sony-camera",
    image: "/demo/reseller/camera.webp",
    title: "Sony mirrorless camera body with three lenses",
    shortName: "Sony Alpha camera kit",
    price: 895,
    condition: "Good",
    category: "Cameras & Photo",
    pricingStory: "comps",
    details: ["Sony mirrorless camera body", "Three lenses shown", "Black camera-and-lens kit"],
    alt: "Black Sony mirrorless camera body arranged with three camera lenses on a dark surface",
  },
  {
    slug: "reseller-iphone-15",
    image: "/demo/reseller/iphone-15.webp",
    title: "Apple iPhone 15, blue",
    shortName: "iPhone 15",
    price: 499,
    condition: "Good",
    category: "Cell Phones & Accessories",
    pricingStory: "comps",
    details: ["Apple iPhone 15", "Blue finish", "Dual-camera rear system"],
    alt: "Blue Apple iPhone 15 resting in sunlight with its dual-camera system visible",
  },
  {
    slug: "reseller-airpods-max",
    image: "/demo/reseller/airpods-max.webp",
    title: "Apple AirPods Max, space gray",
    shortName: "AirPods Max",
    price: 329,
    condition: "Good",
    category: "Consumer Electronics",
    pricingStory: "comps",
    details: ["Apple AirPods Max", "Space gray finish", "Over-ear design"],
    alt: "Space gray Apple AirPods Max over-ear headphones on a warm brown surface",
  },
  {
    slug: "reseller-keychron",
    image: "/demo/reseller/keychron.webp",
    title: "Keychron mechanical keyboard, black and orange",
    shortName: "Keychron keyboard",
    price: 79,
    condition: "Like new",
    category: "Computers & Accessories",
    pricingStory: "comps",
    details: ["Keychron mechanical keyboard", "Black keycaps with orange accents", "Compact desktop layout"],
    alt: "Compact black Keychron mechanical keyboard with orange accent keys on a marble surface",
  },
  {
    slug: "reseller-charizard",
    image: "/demo/reseller/charizard.webp",
    title: "Holographic Charizard Pokémon trading card",
    shortName: "Charizard trading card",
    price: 48,
    condition: "Good",
    category: "Collectibles",
    pricingStory: "comps",
    details: ["Charizard Pokémon card", "Holographic finish", "Single unslabbed card"],
    alt: "Holographic Charizard Pokémon trading card standing upright on a dark surface",
  },
  {
    slug: "reseller-air-jordan-pair",
    image: "/demo/reseller/air-jordan-pair.webp",
    title: "White Air Jordan sneakers, pair",
    shortName: "White Air Jordan pair",
    price: 110,
    condition: "Good",
    category: "Clothing & Shoes",
    pricingStory: "comps",
    details: ["Pair of Air Jordan sneakers", "White leather uppers", "Red Wings logos on the heels"],
    alt: "Pair of white Air Jordan sneakers photographed heel-first against a dark background",
  },
  {
    slug: "reseller-switch-2",
    image: "/demo/reseller/switch-2.webp",
    title: "Nintendo Switch 2 handheld console",
    shortName: "Nintendo Switch 2",
    price: 415,
    condition: "Like new",
    category: "Video Games & Consoles",
    pricingStory: "comps",
    details: ["Nintendo Switch 2 console", "Joy-Con controllers attached", "Screen and controls shown"],
    alt: "Nintendo Switch 2 handheld console with attached Joy-Con controllers in soft window light",
  },
  {
    slug: "reseller-galaxy-watch",
    image: "/demo/reseller/galaxy-watches.webp",
    title: "Samsung Galaxy Watch Ultra and Watch 7 pair",
    shortName: "Samsung Galaxy watches",
    price: 399,
    condition: "Like new",
    category: "Watches",
    pricingStory: "comps",
    details: ["Two Samsung Galaxy smartwatches", "Watch Ultra and Watch 7", "Displays powered on"],
    alt: "Two powered-on Samsung Galaxy smartwatches held side by side",
  },
  // The new how-it-works PIPELINE HERO (replaces the Canon AE-1). A real Acer
  // Predator Helios 300 with readable on-body markings (Predator Helios 300 /
  // Core i7 / GeForce RTX / 144Hz) that drive the identify OCR, and strong sold
  // comps for the price step. Four verified-distinct angles staged for the snap
  // step (a1 open straight-on, a2 open night, a3 closed lid, a4 boot screen).
  {
    slug: "acer-predator",
    image: "/demo/authentic/acer-predator-a1-open.jpg",
    title: "Acer Predator Helios 300 gaming laptop, Core i7 / RTX",
    shortName: "Acer Predator Helios",
    price: 550,
    condition: "Good",
    category: "Computers & Accessories",
    pricingStory: "comps",
    details: [
      "Predator Helios 300, Intel Core i7",
      "GeForce RTX graphics, 144Hz display",
      "RGB keyboard, powers on, light wear",
    ],
    alt: "An open Acer Predator Helios 300 gaming laptop with an RGB-backlit keyboard, model badges visible below the screen",
  },
];

export const DEMO_PRODUCTS_BY_SLUG: Record<string, DemoProduct> =
  Object.fromEntries(DEMO_PRODUCTS.map((p) => [p.slug, p]));

/** Which catalog products define each high-salience marketing surface. */
export const DEMO_SURFACE_ASSIGNMENTS: Record<string, string[]> = {
  // --- Real dev-preview capture suite (see remotion/INTEGRATION.md) ---
  // One real PlayStation 5 listing anchors the complete story so the six clips
  // read as one reseller workflow, not six unrelated stock-photo examples.
  "step-snap": ["reseller-ps5"],
  "step-identify": ["reseller-ps5"],
  "step-price": ["reseller-ps5"],
  "step-write": ["reseller-ps5"],
  "step-publish": ["reseller-ps5"],
  "buyer-qa": ["reseller-ps5", "reseller-switch-2", "reseller-sony-camera"],
  "inbox-qa": ["reseller-ps5", "reseller-switch-2", "reseller-sony-camera"],
  // --- Static page surfaces ---
  // #136: a deliberate tech / gaming / streetwear haul. The broader catalog
  // still supports generic household items, but none define a primary surface.
  "landing-carousel": [
    "reseller-ps5",
    "reseller-iphone-15",
    "reseller-sony-camera",
    "reseller-switch-2",
    "reseller-dualsense",
    "reseller-charizard",
    "reseller-air-jordan-pair",
    "reseller-keychron",
    "reseller-airpods-max",
    "reseller-galaxy-watch",
  ],
  // The anchor PlayStation 5 listing rendered three platform-fluent ways.
  "landing-storefronts": ["reseller-ps5"],
  // The home "From shelf to sold in three moves" prelude — one recognizable,
  // shippable item shown captured → priced → listed.
  "landing-three-moves": ["reseller-ps5"],
  // Hero ScanShowcase — the same coherent haul, with the PS5 anchor first.
  // Repetition across primary surfaces is intentional: this is one seller's
  // inventory, not a grab bag assembled independently per component.
  "landing-hero-scan": [
    "reseller-ps5",
    "reseller-iphone-15",
    "reseller-sony-camera",
    "reseller-switch-2",
    "reseller-charizard",
    "reseller-air-jordan-pair",
    "reseller-keychron",
    "reseller-airpods-max",
  ],
  // The pricing waterfall on /how-it-works (last section before the CTA).
  "hiw-waterfall": ["reseller-ps5"],
  "how-it-works": ["reseller-ps5"], // + embeds the step-* clips above
  // Three items exclusive to the logged-in dashboard folder (ordered
  // shortest→longest name for the folder's narrow→wide papers).
  "dashboard-folder": ["a-litterbox", "a-bowls", "a-chest"],
};
