/**
 * Vision module public surface (issue #6). Real single-shot multimodal extraction
 * → Zod-validated attributes + a flagged identification, composed into the existing
 * `Pipeline` seam. Swap `createVisionPipeline` in for the stub at the upload call site.
 */
export {
  extractItemAttributes,
  createOpenAIVisionGenerate,
  deriveIdentification,
  identificationEvidence,
  DEFAULT_VISION_MODEL,
  MIN_IMAGES,
  MAX_IMAGES,
  type VisionGenerate,
  type VisionGenerateResult,
  type VisionImageInput,
  type ExtractItemAttributesInput,
  type ExtractItemAttributesResult,
} from "./extract";
export {
  resolvePhotoImages,
  resolvePhotoImageData,
  signPhotoUrlMap,
  PHOTOS_BUCKET,
  DEFAULT_SIGNED_URL_TTL_SECONDS,
  type BatchSignedUrlClient,
  type SignedUrlClient,
  type DownloadClient,
  type PhotoImageData,
} from "./photos";
export {
  createVisionPipeline,
  createVisionPipelineStages,
  type CreateVisionPipelineOptions,
  type VisionPipelineStages,
  type IdentifiedVisionPipelineStage,
  type GeneratedVisionPipelineStage,
} from "./pipeline";
export {
  extractGarmentMeasurements,
  createGarmentMeasureGenerate,
  gateMeasurements,
  tapeVisible,
  parseMeasurementEdits,
  classifyGarment,
  garmentClassOf,
  isGarment,
  needsReference,
  garmentMeasurementsSchema,
  formatMeasurement,
  trimInches,
  measurementWords,
  confirmedMeasurementPhrases,
  listingFactAttributes,
  measurementDraftSchema,
  measurementDraftsSchema,
  measurementResponseSchema,
  storedMeasurementMethodSchema,
  MEASUREMENT_NAMES,
  MEASUREMENT_LABELS,
  GARMENT_CLASSES,
  GARMENT_MEASUREMENT_SETS,
  AUTO_SUGGEST_MEASUREMENTS,
  TAPE_GATED_MEASUREMENTS,
  type MeasureGenerate,
  type MeasurementDraft,
  type MeasurementName,
  type MeasurementResponse,
  type MeasurementMethod,
  type StoredMeasurementMethod,
  type GarmentClass,
  type ExtractGarmentMeasurementsInput,
  type ExtractGarmentMeasurementsResult,
  type SubmittedMeasurement,
} from "./measurements";
